#!/bin/bash
if [ "$#" != 1 ]; then
    echo "Usage: $0 <release-number>"
    exit 1;
fi

# The whole version number (3 numbers separated by periods)
version="$1"
# shellcheck disable=SC2206 # don't have to worry abour word splitting
AVERSION=(${version//./ })
MAJOR_VER=${AVERSION[0]}
MINOR_VER=${AVERSION[1]}
if [ "$MINOR_VER" -eq 0 ]; then
    ver=$MAJOR_VER.0
else
    ver=$MAJOR_VER.x
fi

rm -rf /tmp/$version

if [ -d /tmp/$version ]; then
    echo "/tmp/$version already exists!"
    exit 1
fi

mkdir /tmp/$version
mkdir /tmp/$version/manual
mkdir /tmp/$version/tarballs
mkdir /tmp/$version/rpm
mkdir /tmp/$version/debian
mkdir /tmp/$version/ubuntu

tag=$(echo $version | sed 's/\./_/g')

echo Copying Manual...
wget https://htcondor.readthedocs.io/_/downloads/en/v$tag/htmlzip/ -O /tmp/$version/manual/index.html.zip
wget https://htcondor.readthedocs.io/_/downloads/en/v$tag/pdf/ -O /tmp/$version/manual/htcondor-${version}.pdf
wget https://htcondor.readthedocs.io/_/downloads/en/v$tag/epub/ -O /tmp/$version/manual/htcondor-${version}.epub
echo Copying tarballs...
(cd /p/condor/public/html/htcondor/tarball/$ver/$version/release; cp -av * /tmp/$version/tarballs/)
echo Copying RPMs from RPM repository...
(cd /p/condor/public/html/htcondor/repo; tar cf - $(find -L $ver* -name \*$version-1\*) | (cd /tmp/$version/rpm; tar xvfp -))
echo Copying debs from Debian repository...
(cd /p/condor/public/html/htcondor/repo; tar cf - $(find -L debian/$ver* -name \*$version-1\*) | (cd /tmp/$version/debian; tar xvfp -))
echo Copying debs from Ubuntu repository...
(cd /p/condor/public/html/htcondor/repo; tar cf - $(find -L ubuntu/$ver* -name \*$version-1\*) | (cd /tmp/$version/ubuntu; tar xvfp -))

du -shx /tmp/$version/*
