#!/bin/bash
# Usage: publish-release 8.x.y build-id (release, rc, daily, fips)


batlab='condorauto@batlab.chtc.wisc.edu'

usage() {
    echo "Usage: $(basename $0) version build_id repo build_date"
    echo
    echo version examples: 8.8.2, 8.9.1
    echo build_id example: 543234
    echo repo examples: release, rc, daily, fips, etc
    echo build_date example: 20201019

}
if [ $# -ne 4 ]; then
    usage
    exit 1
fi

version=(${1//./ })
major_ver=${version[0]}
minor_ver=${version[1]}
patch_ver=${version[2]}
version=$1
repo_version="${major_ver}.${minor_ver}"

build_id=$2

repo=$3

build_date="-${4}"

echo "Version: ${version}, Build ID: ${build_id}, Repo: ${repo}, Build Date: ${4}"

read -p "Continue? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1 # handle exits from shell or function but don't exit interactive shell
fi

# Old key, issued 2013, 2048 bits
key=670079F6

# Stable series
if [ $repo_version = '9.0' ]; then
    if [ $repo = 'daily' ]; then
        # HTCondor 9.0 Daily Key
        key=8A314675
    else
        # HTCondor 9.0 Key
        key=748E8328
    fi
fi

# Feature serires
if [ $repo_version = '9.1' ]; then
    if [ $repo = 'daily' ]; then
        # HTCondor 9.1 Daily Key
        key=EC836AA7
    else
        # HTCondor 9.1 Key
        key=6D4CA7CD
    fi
fi

if [ $repo = 'release' ]; then
    build_date=""
fi

if [ $repo = 'private' ]; then
    build_date=""
fi

killall gpg-agent
eval $(gpg-agent --daemon --enable-ssh-support --write-env-file "${HOME}/.gpg-agent-info" --no-use-standard-socket)

win64=8
macosx=15

ssh $batlab "cd /scratch && /scratch/tim/new_stage $version $build_id"
ssh $batlab "cd /scratch/condor_${version}-${build_id} && ./get_${build_id}"
rsync -av $batlab:/scratch/condor_${version}-${build_id} /tmp/

files=$(cd /tmp/condor_${version}-${build_id}/public; find -name \*${version}-\* | wc -l)

release="/tmp/condor_${version}-${build_id}/public"
tarball="/p/condor/public/html/htcondor/tarball/${repo_version}/${version}/${repo}"
repository="/p/condor/public/html/htcondor/repo"

if [ $files -eq 0 ]; then
    echo Version mismatch!
    ssh $batlab rm -rf /scratch/condor_${version}-${build_id}
    echo Clean up temp space
    rm -rf ${release}
    exit 1
fi

#Verify downloads
echo Checking for all platforms...

# Plaforms going away
if [ "${major_ver}.${minor_ver}" = "9.0" ]; then
    for platform in x86_64_Debian9; do
        if [ ! -d ${release}/${platform} ]; then
            echo ERROR: $platform not present!
        fi
    done
fi

for platform in x86_64_AmazonLinux2 \
                x86_64_CentOS7 x86_64_CentOS8 \
                x86_64_Debian10 \
                x86_64_MacOSX${macosx} \
                x86_64_Ubuntu18 x86_64_Ubuntu20 \
                x86_64_Windows${win64}; do
    if [ ! -d ${release}/${platform} ]; then
        echo ERROR: $platform not present!
    fi
done

read -p "Continue? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    ssh $batlab rm -rf /scratch/condor_${version}-${build_id}
    echo Clean up temp space
    rm -rf ${release}
    exit 1
fi

if [ $repo = 'release' ]; then
    ssh $batlab nmi_pin --days=365 --force ${build_id}
else
    ssh $batlab rm -rf /scratch/condor_${version}-${build_id}
fi

# Move tarballs into place
echo Publish tarballs...
# rm -rf ${tarball}
mkdir -p ${tarball}

platforms="x86_64_AmazonLinux2 x86_64_CentOS7 x86_64_CentOS8 x86_64_Debian10 x86_64_Ubuntu18 x86_64_Ubuntu20"
if [ $repo = 'daily' ]; then
    platforms="$platforms x86_64_Fedora32"
fi

# Platforms on the way out
if [ "${major_ver}.${minor_ver}" = "9.0" ]; then
    platforms="$platforms x86_64_Debian9"
fi

for platform in $platforms; do
    echo ======= $platform =======
    mv ${release}/${platform}/condor-${version}*-${platform}-stripped.tar.gz \
       ${tarball}/condor-${version}${build_date}-${platform}-stripped.tar.gz
done

echo ======= x86_64_MacOSX =======
mv ${release}/x86_64_MacOSX${macosx}/condor-${version}*-x86_64_MacOSX${macosx}-stripped.tar.gz \
   ${tarball}/condor-${version}${build_date}-x86_64_MacOSX-stripped.tar.gz


echo ======= x86_64_Windows =======
mv ${release}/x86_64_Windows${win64}/condor-${version}-${build_id}-Windows${win64}-x64.zip \
   ${tarball}/condor-${version}${build_date}-Windows-x64.zip

mv ${release}/x86_64_Windows${win64}/condor-${version}-${build_id}-Windows${win64}-x64.msi \
   ${tarball}/condor-${version}${build_date}-Windows-x64.msi

# Copy source tarball from most earliest Debian build
if [ "${major_ver}.${minor_ver}" = "9.0" ]; then
    src_platform="x86_64_Debian9"
else
    src_platform="x86_64_Debian10"
fi
cp -p ${release}/${src_platform}/condor_${version}.orig.tar.gz \
      ${tarball}/condor-${version}${build_date}-src.tar.gz

echo Sign tarballs...
(cd ${tarball} && rm -f sha256sum.txt.gpg)
(cd ${tarball} && sha256sum *${version}${build_date}* >> sha256sum.txt)
(cd ${tarball} && gpg --sign -u 0x$key sha256sum.txt)

# Move RPMs into place

echo Sign RPMs...
rpmsign --addsign --key-id=$key ${release}/*/*.rpm

update_rpm_repo() {
    platform_name=$1
    platform=$2

    mkdir -p ${repository}/${repo_version}/${platform}/${repo}
    mkdir -p ${repository}/${repo_version}/${platform}/${repo}/SRPMS
    mkdir -p ${repository}/${repo_version}/${platform}/${repo}/debug

    echo ======= ${repo_version}/${platform}/${repo}/SRPMS =======
    mv ${release}/${platform_name}/*.src.rpm \
       ${repository}/${repo_version}/${platform}/${repo}/SRPMS
    createrepo --update \
       ${repository}/${repo_version}/${platform}/${repo}/SRPMS
    gpg --detach-sign -u 0x$key --yes --armor \
       ${repository}/${repo_version}/${platform}/${repo}/SRPMS/repodata/repomd.xml

    echo ======= ${repo_version}/${platform}/${repo}/debug =======
    mv ${release}/${platform_name}/*-debug*.rpm \
       ${repository}/${repo_version}/${platform}/${repo}/debug
    createrepo --update \
       ${repository}/${repo_version}/${platform}/${repo}/debug
    gpg --detach-sign -u 0x$key --yes --armor \
       ${repository}/${repo_version}/${platform}/${repo}/debug/repodata/repomd.xml

    echo ======= ${repo_version}/${platform}/${repo} =======
    mv ${release}/${platform_name}/*.rpm \
       ${repository}/${repo_version}/${platform}/${repo}
    createrepo --excludes='debug/*' --excludes='SRPMS/*' --update \
       ${repository}/${repo_version}/${platform}/${repo}
    gpg --detach-sign -u 0x$key --yes --armor \
       ${repository}/${repo_version}/${platform}/${repo}/repodata/repomd.xml
}

update_rpm_repo "x86_64_AmazonLinux2" "amzn2"
update_rpm_repo "x86_64_CentOS7" "el7"
update_rpm_repo "x86_64_CentOS8" "el8"
update_rpm_repo "x86_64_Fedora32" "fc32"

# Update Debian/Ubuntu repositories

drop_deb_publish () {
    distro=$1
    code_name=$2

    if $(aptly publish show $code_name $distro/$deb_repo_name > /dev/null 2>&1); then
        aptly publish drop $code_name $distro/$deb_repo_name
    fi
}

drop_deb_repo () {
    distro=$1
    code_name=$2

    if $(aptly repo show $deb_repo_name-$code_name > /dev/null 2>&1); then
        aptly repo drop $deb_repo_name-$code_name
    fi
}

update_deb_repo () {
    platform_name=$1
    distro=$2
    code_name=$3

    if ! $(aptly repo show $deb_repo_name-$code_name > /dev/null 2>&1); then
        aptly repo create --distribution=$code_name $deb_repo_name-$code_name
        # If we just created the repository, be sure to add the necessary
        # externals
        aptly repo add $deb_repo_name-$code_name /nobackup/tim/externals/${platform_name}
    fi
    aptly repo add $deb_repo_name-$code_name ${release}/${platform_name}

    if $(aptly publish show $code_name $distro/$deb_repo_name > /dev/null 2>&1); then
        aptly publish update -gpg-key=$key $code_name $distro/$deb_repo_name
    else
        aptly publish repo -gpg-key=$key $deb_repo_name-$code_name $distro/$deb_repo_name
    fi
}

deb_repo_name=${major_ver}.${minor_ver}
if [ $repo != 'release' ]; then
    deb_repo_name=${deb_repo_name}-${repo}

    echo "Dropping published repostories"
    # Platforms on the way out
    if [ "${major_ver}.${minor_ver}" = "9.0" ]; then
        drop_deb_publish "ubuntu" "xenial"
    fi

    drop_deb_publish "debian" "stretch"
    drop_deb_publish "debian" "buster"
    drop_deb_publish "ubuntu" "bionic"
    drop_deb_publish "ubuntu" "focal"

    # Newer platforms
    if [ "${major_ver}.${minor_ver}" != "9.0" ]; then
        echo No new platforms
    fi

    echo "Dropping repostories"
    # Platforms on the way out
    if [ "${major_ver}.${minor_ver}" = "9.0" ]; then
        drop_deb_repo "ubuntu" "xenial"
    fi

    drop_deb_repo "debian" "stretch"
    drop_deb_repo "debian" "buster"
    drop_deb_repo "ubuntu" "bionic"
    drop_deb_repo "ubuntu" "focal"

    # Newer platforms
    if [ "${major_ver}.${minor_ver}" != "9.0" ]; then
        echo No new platforms
    fi

    aptly db cleanup
fi

echo "Updating published repostories"
# Platforms on the way out
if [ "${major_ver}.${minor_ver}" = "9.0" ]; then
    update_deb_repo "x86_64_Debian9" "debian" "stretch"
fi

update_deb_repo "x86_64_Debian10" "debian" "buster"
update_deb_repo "x86_64_Ubuntu18" "ubuntu" "bionic"
update_deb_repo "x86_64_Ubuntu20" "ubuntu" "focal"

# Newer platforms
if [ "${major_ver}.${minor_ver}" != "9.0" ]; then
    echo No new platforms
fi

# Put the new files in the pool
rsync -av /nobackup/tim/aptly/public/debian/${deb_repo_name}/pool /p/condor/public/html/htcondor/repo/debian/${deb_repo_name}/
# Update the dists to point to the new files
rsync -av /nobackup/tim/aptly/public/debian/${deb_repo_name}/dists /p/condor/public/html/htcondor/repo/debian/${deb_repo_name}/
# Delete any old files
rsync -av --delete /nobackup/tim/aptly/public/debian/${deb_repo_name} /p/condor/public/html/htcondor/repo/debian/

# Put the new files in the pool
rsync -av /nobackup/tim/aptly/public/ubuntu/${deb_repo_name}/pool /p/condor/public/html/htcondor/repo/ubuntu/${deb_repo_name}/
# Update the dists to point to the new files
rsync -av /nobackup/tim/aptly/public/ubuntu/${deb_repo_name}/dists /p/condor/public/html/htcondor/repo/ubuntu/${deb_repo_name}/
# Delete any old files
rsync -av --delete /nobackup/tim/aptly/public/ubuntu/${deb_repo_name} /p/condor/public/html/htcondor/repo/ubuntu/


# Clean up temp space
echo Clean up temp space
rm -rf ${release}
