#!/bin/bash
set -e
# splice in newer Pelican for CentOS7 tarballs

usage() {
    echo "Usage: $(basename "$0") tarball"
}
if [ $# -ne 1 ]; then
    usage
    exit 1
fi

tarball=$1

echo "Updating Pelican in $tarball..."

mkdir /tmp/tarball
(cd /tmp/tarball; tar xfpz -) < "$tarball"
pushd /tmp/tarball
tarball_dir=$(echo condor-*-x86_64_CentOS7-stripped)
if [ -d "$tarball_dir" ]; then
    cd "$tarball_dir"
    rm -r usr/share/doc/pelican-*
    rpm2cpio /nobackup/tim/externals/23.x/x86_64_CentOS7/pelican-[0-9]*.x86_64.rpm | cpio -imdu --no-absolute-filenames
    rpm2cpio /nobackup/tim/externals/23.x/x86_64_CentOS7/pelican-osdf-compat-[0-9]*.x86_64.rpm | cpio -imdu --no-absolute-filenames
    usr/bin/pelican --version
    cd ..
    tar --create --gzip --owner=0 --group=0 --numeric-owner --file "$tarball_dir.tar.gz" "$tarball_dir"
    rm -rf "$tarball_dir"
    mv "/tmp/tarball/$tarball_dir.tar.gz" "$tarball"
    popd
    rmdir /tmp/tarball
else
    echo ERROR: CentOS7 tarballs only please!
    popd
    rm -rf /tmp/tarball
    exit 1
fi
exit 0
